### ISSUE TITLE
Vercel Deploy Bug: PostgrestError status type error breaking Vercel builds

### ISSUE THREAD

**Issue by alinplotnik** [Code4Good-26B/savionim#29]
We are experiencing recurring Vercel build failures after merging PRs due to a TypeScript error. The build crashes with the following message:
Type error: Property 'status' does not exist on type 'PostgrestError'

Root Cause:
This happens because we are trying to access the HTTP status code directly from the Supabase error object. The PostgrestError type does not contain a status property. The status is actually returned at the root level of the Supabase response alongside data and error.

The Fix Pattern:
We need to extract the status directly from the initial Supabase call instead of the error object.

Here is the correct implementation pattern:

TypeScript
// START OF CHANGE
const { data, error, status: supabaseStatus } = await supabase
  .from("table_name")
  .select()
  .single()

if (error) {
  return Response.json(
    { error: error.message },
    { status: typeof supabaseStatus === "number" ? supabaseStatus : 500 }
  )
}
// END OF CHANGE

task:

Global Refactor: Scan the entire codebase (specifically all API routes) for any usage of error.status or error.code related to Supabase queries and update them to use the destructured status from the response.
